export const types = {
	FETCH_DEVICE_LIST_REQUEST: 'FETCH_DEVICE_LIST_REQUEST',
	FETCH_DEVICE_LIST_SUCCESS: 'FETCH_DEVICE_LIST_SUCCESS',
	FETCH_DEVICE_LIST_ERROR: 'FETCH_DEVICE_LIST_ERROR',
	FETCH_IMAGE_LIST_REQUEST: 'FETCH_IMAGE_LIST_REQUEST',
	FETCH_IMAGE_LIST_SUCCESS: 'FETCH_IMAGE_LIST_SUCCESS',
	FETCH_IMAGE_LIST_ERROR: 'FETCH_IMAGE_LIST_ERROR',
};
